apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-http-server-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ruby-web-server
  template:
    metadata:
      labels:
        app: ruby-web-server
    spec:
      containers:
      - name: ruby-web-server
        image: devopsdeepan/ruby-http-server:latest
        ports:
          - containerPort: 80
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: 80
            initialDelaySeconds: 90
            periodSeconds: 10

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: ruby-http-server-deployment
#   namespace: default
# spec:
#     replicas: 4
#     selector:
#       matchLabels:
#         app: ruby-web-server
#     template:
#       metadata:
#         labels:
#           app: ruby-web-server
#     spec:
#       containers:
#       - name: ruby-web-server
#         image: docker.pkg.github.com/devopsdeepan/ruby-http-server:latest
#         imagePullPolicy: Always
#         ports:
#           - containerPort: 80
#             protocol: TCP
#         livenessProbe:
#           tcpSocket:
#             port: 80
#             initialDelaySeconds: 90
#             periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: rruby-web-server-svc
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ruby-web-server